### ISSUE TITLE
USER STORY: Menu - links to each page 

### ISSUE THREAD

**Issue by kchohanaza** [MarkChips/prevent-awareness#5]
In order to Menu - links to each page as a **user*, I can **click in each page on navigation bar**

### Acceptance Criteria:
- Links that work
- Responsive to different devices and screens
- The formatting of the links are the same?

### Tasks:
- [ ] Gather link information and ensure text is understandable for users
- [ ] Links HTML into Header section

**Comment by Grace-YuGuo** [comment]
### Menu-links to each page set up, works in local environment

### Menu-responsive to mobile screen and tablet screen

### Menu-favicon added into the head(picture used the discussed/agreed logo)

**Comment by Damitwhy** [comment]
I think this is awesome
